# Generated by Django 3.0.1 on 2019-12-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_branch_customer_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customers',
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(default='test', max_length=30, on_delete=django.db.models.deletion.CASCADE, to='todo.Product'),
            preserve_default=False,
        ),
    ]
