# Generated by Django 3.0.1 on 2019-12-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20191224_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(to='todo.Customer'),
        ),
    ]
